### ISSUE TITLE
Contributing?

### ISSUE THREAD

**Issue by 111116** [ddevault/osuweb#12]
I like this project, and I'm looking to develop it into a complete game, which will bring lots of major changes. Please let me know if you'd like me to contribute these changes to your repo in future.

**Comment by ddevault** [comment]
You're better off forking the project and building from there.

**Comment by 111116** [comment]
Yeah of course. I'm already working on a fork. I mean, I'm not sure whether you're willing to accept changes or you just want to keep it simple.

**Comment by ddevault** [comment]
Nah, this project is abandoned. You're better off working on your own terms.

**Comment by 111116** [comment]
Fine. Thanks for replying

**Comment by nyanpasu** [comment]
Nice. Hope you manage to deal with those sound sync issues.
